# =============================================================================
# GoogleFindMyTools – Traccar sync service
#
# Builds a self-contained image by cloning two repositories:
#   1. leonboe1/GoogleFindMyTools  — base project (NovaApi, ProtoDecoders, …)
#   2. Tloxipeuhca/google-tools-traccar-sync — Traccar sync module
#
# The Traccar/ folder and extended requirements.txt from the sync repo are
# overlaid on top of the base project.
#
# Usage (from the Traccar/ directory):
#   docker compose up -d
# =============================================================================

FROM python:3.11-slim

WORKDIR /app

# System packages required by some Python dependencies (frida, cryptography …)
RUN apt-get update && apt-get install -y --no-install-recommends \
        gcc \
        libffi-dev \
        git \
    && rm -rf /var/lib/apt/lists/*

# 1. Clone GoogleFindMyTools – provides NovaApi, ProtoDecoders, main.py, …
RUN git clone --depth 1 https://github.com/leonboe1/GoogleFindMyTools.git .

# 2. Clone the Traccar sync module and overlay it on the base project
RUN git clone --depth 1 https://github.com/Tloxipeuhca/google-tools-traccar-sync.git /app/Traccar \
    && sort -u /app/requirements.txt /app/Traccar/requirements.txt -o /app/requirements.txt

# Install all Python dependencies (merged base + Traccar requirements)
RUN pip install --no-cache-dir -r requirements.txt

# Entrypoint: guard against missing secrets.json before starting the service
RUN printf '#!/bin/sh\n\
# Guard: secrets.json is required to run the service (generated by python main.py)\n\
case "$*" in\n\
    *Traccar.service*)\n\
        if [ ! -s /app/Auth/secrets.json ]; then\n\
            echo "ERROR: Auth/secrets.json not found or empty."\n\
            echo "Run first: docker compose run --rm traccar-sync python main.py"\n\
            exit 1\n\
        fi\n\
        ;;\n\
esac\n\
exec "$@"\n' > /usr/local/bin/docker-entrypoint.sh \
    && chmod +x /usr/local/bin/docker-entrypoint.sh

# Pre-create runtime directories; they will be overridden by bind-mounts at run time
RUN mkdir -p Data logs

EXPOSE 5001

# Keep Python output unbuffered so logs appear immediately in docker logs
ENV PYTHONUNBUFFERED=1

HEALTHCHECK --interval=30s --timeout=10s --start-period=60s --retries=3 \
    CMD python -c "import urllib.request,os; urllib.request.urlopen('http://localhost:'+os.environ.get('PORT','5001')+'/health')" || exit 1

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]

# TRACCAR_SERVER_URL and PORT are injected at runtime via environment variables
# (see docker-compose.yml or pass -e flags to docker run)
CMD ["sh", "-c", "python -m Traccar.service --server-url \"${TRACCAR_SERVER_URL}\" --port \"${PORT:-5001}\""]
